development:
  adapter: postgresql
  encoding: unicode
  database: crowdvocate_development
  pool: 5
  username: crowdvocate
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: crowdvocate_test
  pool: 5
  username: crowdvocate
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: crowdvocate_production
  pool: 5
  username: crowdvocate
  password: